### ISSUE TITLE
Pynq on Zedboard

### ISSUE THREAD

**Issue by r1marcus** [parthpower/DCC_Basic#3]
Hey this is a other topic but i think the fastest way to connect to you.
On your tutorial at https://superuser.blog/pynq-linux-on-zedboard/
is the Download link for the TL;DL way down.
i want to ask can you update the link pls?

greetings
MR

**Comment by parthpower** [comment]
You could contact me on my Twitter @parthpower.

The link is https://drive.google.com/file/d/0B9OutAup6VgTNktMLTRpajBSTk0/view?usp=drivesdk

Will fix it on website ASAP. Thanks.
